import type { Product } from './types';

export const products: Product[] = [
  {
    id: 'prod_1',
    name: 'Ashwagandha Tablets',
    description: 'Natural stress-reliever and vitality booster.',
    price: 499.0,
    category: 'Ayurvedic',
    attributes: ['Stress Relief', 'Vitality'],
    imageId: 'prod_1',
    popularity: 9,
  },
  {
    id: 'prod_2',
    name: 'Triphala Powder',
    description: 'A classic Ayurvedic formula for digestion and detoxification.',
    price: 349.0,
    category: 'Ayurvedic',
    attributes: ['Digestion', 'Detox'],
    imageId: 'prod_2',
    popularity: 8,
  },
  {
    id: 'prod_3',
    name: 'Brahmi Capsules',
    description: 'Enhances cognitive functions and memory.',
    price: 599.0,
    category: 'Ayurvedic',
    attributes: ['Memory', 'Cognitive Health'],
    imageId: 'prod_3',
    popularity: 7,
  },
  {
    id: 'prod_4',
    name: 'Arnica Montana',
    description: 'Homeopathic remedy for bruises and muscle soreness.',
    price: 249.0,
    category: 'Homeopathic',
    attributes: ['Pain Relief', 'Anti-inflammatory'],
    imageId: 'prod_4',
    popularity: 9,
  },
  {
    id: 'prod_5',
    name: 'Nux Vomica',
    description: 'Used for indigestion, nausea, and hangovers.',
    price: 299.0,
    category: 'Homeopathic',
    attributes: ['Digestion', 'Nausea Relief'],
    imageId: 'prod_5',
    popularity: 6,
  },
  {
    id: 'prod_6',
    name: 'Belladonna',
    description: 'For fever, inflammation, and headache.',
    price: 279.0,
    category: 'Homeopathic',
    attributes: ['Fever Reducer', 'Pain Relief'],
    imageId: 'prod_6',
    popularity: 7,
  },
  {
    id: 'prod_7',
    name: 'Vitamin D3 Softgels',
    description: 'Essential for bone health and immune support.',
    price: 799.0,
    category: 'Supplements',
    attributes: ['Bone Health', 'Immune Support'],
    imageId: 'prod_7',
    popularity: 10,
  },
  {
    id: 'prod_8',
    name: 'Omega-3 Fish Oil',
    description: 'Supports heart and brain health.',
    price: 999.0,
    category: 'Supplements',
    attributes: ['Heart Health', 'Brain Health'],
    imageId: 'prod_8',
    popularity: 9,
  },
  {
    id: 'prod_9',
    name: 'Multivitamin Gummies',
    description: 'A tasty way to get your daily vitamins.',
    price: 649.0,
    category: 'Supplements',
    attributes: ['General Wellness', 'Vitamins'],
    imageId: 'prod_9',
    popularity: 8,
  },
  {
    id: 'prod_10',
    name: 'Paracetamol 500mg',
    description: 'Effective relief from pain and fever.',
    price: 99.0,
    category: 'Allopathic',
    attributes: ['Pain Relief', 'Fever Reducer'],
    imageId: 'prod_10',
    popularity: 10,
  },
  {
    id: 'prod_11',
    name: 'Amoxicillin 250mg',
    description: 'Common antibiotic for bacterial infections. Prescription needed.',
    price: 199.0,
    category: 'Allopathic',
    attributes: ['Antibiotic', 'Infection'],
    imageId: 'prod_11',
    popularity: 7,
  },
  {
    id: 'prod_12',
    name: 'Ibuprofen 200mg',
    description: 'Reduces inflammation and pain.',
    price: 149.0,
    category: 'Allopathic',
    attributes: ['Pain Relief', 'Anti-inflammatory'],
    imageId: 'prod_12',
    popularity: 9,
  },
  {
    id: 'prod_13',
    name: 'Turmeric Capsules',
    description: 'Natural anti-inflammatory with curcumin.',
    price: 450.0,
    category: 'Ayurvedic',
    attributes: ['Anti-inflammatory', 'Joint Health'],
    imageId: 'prod_13',
    popularity: 8,
  },
  {
    id: 'prod_14',
    name: 'Calcium + Magnesium',
    description: 'For strong bones and muscle function.',
    price: 550.0,
    category: 'Supplements',
    attributes: ['Bone Health', 'Muscle Function'],
    imageId: 'prod_14',
    popularity: 7,
  },
  {
    id: 'prod_15',
    name: 'Cetirizine 10mg',
    description: 'Antihistamine for allergy relief.',
    price: 75.0,
    category: 'Allopathic',
    attributes: ['Allergy Relief', 'Antihistamine'],
    imageId: 'prod_15',
    popularity: 9,
  },
  {
    id: 'prod_16',
    name: 'Chyawanprash',
    description: 'Ayurvedic jam for boosting immunity.',
    price: 399.0,
    category: 'Ayurvedic',
    attributes: ['Immune Support', 'Vitality'],
    imageId: 'prod_16',
    popularity: 10,
  },
  {
    id: 'prod_17',
    name: 'Lycopodium Clavatum',
    description: 'Homeopathic remedy for bloating and gas.',
    price: 260.0,
    category: 'Homeopathic',
    attributes: ['Digestion', 'Bloating'],
    imageId: 'prod_17',
    popularity: 5,
  }
];
