import type { Product } from './types';

export const products: Product[] = [
  {
    id: 'prod_1',
    name: 'Ashwagandha Tablets',
    description: 'Natural stress-reliever and vitality booster.',
    price: 15.99,
    category: 'Ayurvedic',
    attributes: ['Stress Relief', 'Vitality'],
    imageId: 'prod_1',
    popularity: 9,
  },
  {
    id: 'prod_2',
    name: 'Triphala Powder',
    description: 'A classic Ayurvedic formula for digestion and detoxification.',
    price: 12.5,
    category: 'Ayurvedic',
    attributes: ['Digestion', 'Detox'],
    imageId: 'prod_2',
    popularity: 8,
  },
  {
    id: 'prod_3',
    name: 'Brahmi Capsules',
    description: 'Enhances cognitive functions and memory.',
    price: 18.0,
    category: 'Ayurvedic',
    attributes: ['Memory', 'Cognitive Health'],
    imageId: 'prod_3',
    popularity: 7,
  },
  {
    id: 'prod_4',
    name: 'Arnica Montana',
    description: 'Homeopathic remedy for bruises and muscle soreness.',
    price: 9.99,
    category: 'Homeopathic',
    attributes: ['Pain Relief', 'Anti-inflammatory'],
    imageId: 'prod_4',
    popularity: 9,
  },
  {
    id: 'prod_5',
    name: 'Nux Vomica',
    description: 'Used for indigestion, nausea, and hangovers.',
    price: 11.25,
    category: 'Homeopathic',
    attributes: ['Digestion', 'Nausea Relief'],
    imageId: 'prod_5',
    popularity: 6,
  },
  {
    id: 'prod_6',
    name: 'Belladonna',
    description: 'For fever, inflammation, and headache.',
    price: 10.5,
    category: 'Homeopathic',
    attributes: ['Fever Reducer', 'Pain Relief'],
    imageId: 'prod_6',
    popularity: 7,
  },
  {
    id: 'prod_7',
    name: 'Vitamin D3 Softgels',
    description: 'Essential for bone health and immune support.',
    price: 22.0,
    category: 'Supplements',
    attributes: ['Bone Health', 'Immune Support'],
    imageId: 'prod_7',
    popularity: 10,
  },
  {
    id: 'prod_8',
    name: 'Omega-3 Fish Oil',
    description: 'Supports heart and brain health.',
    price: 25.5,
    category: 'Supplements',
    attributes: ['Heart Health', 'Brain Health'],
    imageId: 'prod_8',
    popularity: 9,
  },
  {
    id: 'prod_9',
    name: 'Multivitamin Gummies',
    description: 'A tasty way to get your daily vitamins.',
    price: 19.99,
    category: 'Supplements',
    attributes: ['General Wellness', 'Vitamins'],
    imageId: 'prod_9',
    popularity: 8,
  },
  {
    id: 'prod_10',
    name: 'Paracetamol 500mg',
    description: 'Effective relief from pain and fever.',
    price: 5.99,
    category: 'Allopathic',
    attributes: ['Pain Relief', 'Fever Reducer'],
    imageId: 'prod_10',
    popularity: 10,
  },
  {
    id: 'prod_11',
    name: 'Amoxicillin 250mg',
    description: 'Common antibiotic for bacterial infections. Prescription needed.',
    price: 14.75,
    category: 'Allopathic',
    attributes: ['Antibiotic', 'Infection'],
    imageId: 'prod_11',
    popularity: 7,
  },
  {
    id: 'prod_12',
    name: 'Ibuprofen 200mg',
    description: 'Reduces inflammation and pain.',
    price: 8.5,
    category: 'Allopathic',
    attributes: ['Pain Relief', 'Anti-inflammatory'],
    imageId: 'prod_12',
    popularity: 9,
  },
];
